[ODBC] fix SQLColAttribute to return length of data even if no buffer…
duckdb/duckdb-odbc pull request #37
Opened 2024-10-27 18:09 UTC by Wonixen

According to documentation when SQLColAttribute  is called If CharacterAttributePtr is NULL, StringLengthPtr will still return the total number of bytes (excluding the null-termination character for character data) available to return in the buffer pointed to by CharacterAttributePtr.

2024-12-25 23:37 UTC, Wonixen reviewed
certain applications use this functionality to get buffer length before allocating memory

2025-04-08 13:41 UTC, maiadegraaf requested changes
Thanks for your PR! Looks good to me, and thanks for adding the additional tests. I have one nit and then it should be good to go!

2025-04-08 13:41 UTC, maiadegraaf commented on src/statement/statement.cpp
> +	}
Nit:

```suggestion
        // user only wants the size of the character attribute
        if (character_attribute_ptr == nullptr && string_length_ptr) {
            *string_length_ptr = str.size();
            return SQL_SUCCESS;
        }
```

2025-04-13 19:44 UTC, staticlibs commented
@Wonixen 

Thanks for the PR! Just FYI, I took a liberty to re-submit this PR in #104 adding you in a `Co-authored-by` field. Please let me know if you prefer to proceed with this original PR instead.

2025-04-16 11:20 UTC, closed without merging